// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Migration.Models.ModelsWinLas;

namespace Migration;

public partial class WinLasDbContext : DbContext
{


    public virtual DbSet<WLANST> WLANSTs { get; set; }

    public virtual DbSet<WLANSTGRENAR> WLANSTGRENARs { get; set; }

    public virtual DbSet<WLAVVIKANDECHEF> WLAVVIKANDECHEFs { get; set; }

    public virtual DbSet<WLBLANDAT> WLBLANDATs { get; set; }

    public virtual DbSet<WLENHETER> WLENHETERs { get; set; }

    public virtual DbSet<WLGUSER> WLGUSERs { get; set; }

    public virtual DbSet<WLGUSERDATum> WLGUSERDATAs { get; set; }

    public virtual DbSet<WLJOURNAL> WLJOURNALs { get; set; }

    public virtual DbSet<WLJOURTABELL> WLJOURTABELLs { get; set; }

    public virtual DbSet<WLKOMPETEN> WLKOMPETENs { get; set; }

    public virtual DbSet<WLKOMPTAB> WLKOMPTABs { get; set; }

    public virtual DbSet<WLLETTER> WLLETTERs { get; set; }

    public virtual DbSet<WLLOGG> WLLOGGs { get; set; }

    public virtual DbSet<WLMALLAR> WLMALLARs { get; set; }

    public virtual DbSet<WLORGTRADET> WLORGTRADETs { get; set; }

    public virtual DbSet<WLPERSDATum> WLPERSDATAs { get; set; }

    public virtual DbSet<WLPERSONAL> WLPERSONALs { get; set; }

    public virtual DbSet<WLPERSONID_ORGID> WLPERSONID_ORGIDs { get; set; }

    public virtual DbSet<WLRTFDOK> WLRTFDOKs { get; set; }

    public virtual DbSet<WLTEMP> WLTEMPs { get; set; }

    public virtual DbSet<WLTXTDOK> WLTXTDOKs { get; set; }
    private readonly string _connectionString;

    public WinLasDbContext( string connectionString)
    {
        _connectionString = connectionString;
    }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(_connectionString);
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<WLANST>(entity =>
        {
            entity.HasKey(e => new { e.PERSONID, e.LOPNR }).HasName("PK__WLANST__26DDC61EE05B927A");

            entity.ToTable("WLANST");

            entity.Property(e => e.ANST1)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.ANST2)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.ANST3)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.ANST4)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.ANST5)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.ANST6)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.ANST7)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.ANST8)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.REGSIGN)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.REGTID)
                .HasMaxLength(19)
                .IsUnicode(false)
                .HasDefaultValue("");
        });

        modelBuilder.Entity<WLANSTGRENAR>(entity =>
        {
            entity.HasKey(e => new { e.PERSONID, e.LOPNR }).HasName("PK__WLANSTGR__26DDC61E24B3E2B1");

            entity.ToTable("WLANSTGRENAR");

            entity.Property(e => e.AID)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.ANST)
                .HasMaxLength(170)
                .IsUnicode(false);
            entity.Property(e => e.ANSTNR)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.ANSTRAD_ID)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.ASTEGRP)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.AVTALOMR)
                .HasMaxLength(5)
                .IsUnicode(false)
                .UseCollation("Finnish_Swedish_CS_AS");
            entity.Property(e => e.BEFATTNING)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.BEFGRP)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.DISP1)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.DISP2)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.FORV_KORT)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.GREN)
                .HasMaxLength(140)
                .IsUnicode(false);
            entity.Property(e => e.LONEFORM)
                .HasMaxLength(5)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.ORGID)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.REGSIGN)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.REGTID)
                .HasMaxLength(19)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.SYSSGR)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.WL_TYP)
                .HasMaxLength(5)
                .IsUnicode(false)
                .HasDefaultValue("");
        });

        modelBuilder.Entity<WLAVVIKANDECHEF>(entity =>
        {
            entity.HasKey(e => new { e.PERSONID, e.CHEFPERSONID }).HasName("PK__WLAVVIKA__2AEE1C3BFB3DFB94");

            entity.ToTable("WLAVVIKANDECHEF");

            entity.Property(e => e.GTOM)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.REGSIGN)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.REGTID)
                .HasMaxLength(19)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.STATUS)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasDefaultValue(" ");
        });

        modelBuilder.Entity<WLBLANDAT>(entity =>
        {
            entity.HasKey(e => e.RAD).HasName("PK__WLBLANDA__CAFF8038C689583C");

            entity.ToTable("WLBLANDAT");

            entity.Property(e => e.RAD).ValueGeneratedNever();
            entity.Property(e => e.KOLUMN_A)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.KOLUMN_B)
                .HasMaxLength(3000)
                .IsUnicode(false);
            entity.Property(e => e.REGSIGN)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.REGTID)
                .HasMaxLength(19)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.TYP)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
        });

        modelBuilder.Entity<WLENHETER>(entity =>
        {
            entity.HasKey(e => e.LOPNR).HasName("PK__WLENHETE__F5BE580361222CDF");

            entity.ToTable("WLENHETER");

            entity.Property(e => e.LOPNR).ValueGeneratedNever();
            entity.Property(e => e.ENHET)
                .HasMaxLength(70)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.FORV)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.ID)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .UseCollation("Finnish_Swedish_CS_AS");
            entity.Property(e => e.KONTO)
                .HasMaxLength(70)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.MKE)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.ORGID)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.REDKONTO)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.REGSIGN)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.REGTID)
                .HasMaxLength(19)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.WL_KORT)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.WL_LANG)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasDefaultValue("");
        });

        modelBuilder.Entity<WLGUSER>(entity =>
        {
            entity.HasKey(e => new { e.LOPNR, e.LOGIN }).HasName("PK__WLGUSERS__AB87BA65717517A6");

            entity.ToTable("WLGUSERS");

            entity.Property(e => e.LOGIN)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.BEF)
                .HasMaxLength(25)
                .IsUnicode(false);
            entity.Property(e => e.CHEF)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.FRITT)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.MKE)
                .HasMaxLength(2)
                .IsUnicode(false);
            entity.Property(e => e.NAMN)
                .HasMaxLength(40)
                .IsUnicode(false);
            entity.Property(e => e.PSW)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.PSWDAT)
                .HasMaxLength(8)
                .IsUnicode(false);
            entity.Property(e => e.REGSIGN)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.REGTID)
                .HasMaxLength(19)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.RH)
                .HasMaxLength(25)
                .IsUnicode(false);
            entity.Property(e => e.SIGN)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.TFN)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.TOMDAT).HasDefaultValue(0);
        });

        modelBuilder.Entity<WLGUSERDATum>(entity =>
        {
            entity.HasKey(e => new { e.LOGIN, e.LNR }).HasName("PK__WLGUSERD__0FFB4D99D274473D");

            entity.ToTable("WLGUSERDATA");

            entity.Property(e => e.LOGIN)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.KOLUMN1)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.KOLUMN2)
                .HasMaxLength(300)
                .IsUnicode(false);
            entity.Property(e => e.REGSIGN)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.REGTID)
                .HasMaxLength(19)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.TYP)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
        });

        modelBuilder.Entity<WLJOURNAL>(entity =>
        {
            entity.HasKey(e => new { e.PERSONID, e.LOPNR }).HasName("PK__WLJOURNA__26DDC61E7833565A");

            entity.ToTable("WLJOURNAL");

            entity.Property(e => e.AKTIV)
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.ANTECKN)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.BEFGRP)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.EVENT)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .UseCollation("Finnish_Swedish_CS_AS");
            entity.Property(e => e.FRITEXT)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FV)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.REGSIGN)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.REGTID)
                .HasMaxLength(19)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.SIGN)
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<WLJOURTABELL>(entity =>
        {
            entity.HasKey(e => e.LOPNR).HasName("PK__WLJOURTA__F5BE5803B481567A");

            entity.ToTable("WLJOURTABELL");

            entity.Property(e => e.LOPNR).ValueGeneratedNever();
            entity.Property(e => e.ID)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .UseCollation("Finnish_Swedish_CS_AS");
            entity.Property(e => e.MARKE)
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.RADNR).HasDefaultValue(0);
            entity.Property(e => e.REGSIGN)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.REGTID)
                .HasMaxLength(19)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.TEXT)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<WLKOMPETEN>(entity =>
        {
            entity.HasKey(e => new { e.PERSONID, e.LOPNR }).HasName("PK__WLKOMPET__26DDC61E68B5DC21");

            entity.ToTable("WLKOMPETENS");

            entity.Property(e => e.AR)
                .HasMaxLength(5)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.ATTEST)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.B_L)
                .HasMaxLength(5)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.FRITT)
                .HasMaxLength(25)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.ID)
                .HasMaxLength(11)
                .IsUnicode(false);
            entity.Property(e => e.KOMP)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.REGSIGN)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.REGTID)
                .HasMaxLength(19)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.SIGNDAT)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.SPANN)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.UI)
                .HasMaxLength(25)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.VB1)
                .HasMaxLength(25)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.VB2)
                .HasMaxLength(25)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.VB3)
                .HasMaxLength(25)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.VB4)
                .HasMaxLength(25)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.VB5)
                .HasMaxLength(25)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.VB6)
                .HasMaxLength(25)
                .IsUnicode(false)
                .HasDefaultValue("");
        });

        modelBuilder.Entity<WLKOMPTAB>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__WLKOMPTA__3214EC272D6B1054");

            entity.ToTable("WLKOMPTAB");

            entity.Property(e => e.ID)
                .HasMaxLength(11)
                .IsUnicode(false);
            entity.Property(e => e.DEL1)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.DEL2)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.DEL3)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.DEL4)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.DEL5)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.K_KORT)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.K_LONG)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.MKE)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.REGSIGN)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.REGTID)
                .HasMaxLength(19)
                .IsUnicode(false)
                .HasDefaultValue("");
        });

        modelBuilder.Entity<WLLETTER>(entity =>
        {
            entity.HasKey(e => new { e.RECEIVER, e.SENDER, e.STAMP }).HasName("PK__WLLETTER__35642794A7E7F337");

            entity.ToTable("WLLETTERS");

            entity.Property(e => e.RECEIVER)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.SENDER)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.STAMP)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.COMMON)
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.LETTER)
                .HasMaxLength(2000)
                .IsUnicode(false);
            entity.Property(e => e.REGSIGN)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.REGTID)
                .HasMaxLength(19)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.RUBRIK)
                .HasMaxLength(60)
                .IsUnicode(false);
            entity.Property(e => e.STATUS)
                .HasMaxLength(1)
                .IsUnicode(false);
        });

        modelBuilder.Entity<WLLOGG>(entity =>
        {
            entity.HasKey(e => e.LOPNR).HasName("PK__WLLOGG__F5BE5803A747A530");

            entity.ToTable("WLLOGG");

            entity.Property(e => e.LOPNR).ValueGeneratedNever();
            entity.Property(e => e.ANSTID)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.ANSTTOM).HasDefaultValue(0);
            entity.Property(e => e.BOCK)
                .HasMaxLength(5)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.DISP1)
                .HasMaxLength(5)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.EVENTNR)
                .HasMaxLength(5)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.LOGGDAT).HasDefaultValue(0);
            entity.Property(e => e.NOTERING)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.ORGID)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.REGSIGN)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.REGTID)
                .HasMaxLength(19)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.SIGNATUR)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.TEXT)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.TYP)
                .HasMaxLength(10)
                .IsUnicode(false);
        });

        modelBuilder.Entity<WLMALLAR>(entity =>
        {
            entity.HasKey(e => new { e.LOPNR, e.MALLNAMN }).HasName("PK__WLMALLAR__3AB8076BEC315B6C");

            entity.ToTable("WLMALLAR");

            entity.Property(e => e.MALLNAMN)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.MALLRAD)
                .HasMaxLength(3000)
                .IsUnicode(false);
            entity.Property(e => e.REGSIGN)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.REGTID)
                .HasMaxLength(19)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.SIGNATUR)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
        });

        modelBuilder.Entity<WLORGTRADET>(entity =>
        {
            entity.HasKey(e => new { e.TYP, e.ORGID }).HasName("PK__WLORGTRA__B5BCF28C959FBB50");

            entity.ToTable("WLORGTRADET");

            entity.Property(e => e.TYP)
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.ORGID)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.ORGGREN)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.PARENT)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.REGSIGN)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.REGTID)
                .HasMaxLength(19)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.WL_KORT)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.WL_LANG)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<WLPERSDATum>(entity =>
        {
            entity.HasKey(e => e.PERSONID).HasName("PK__WLPERSDA__0986239E7CA6B0CF");

            entity.ToTable("WLPERSDATA");

            entity.HasIndex(e => e.PERSONNR, "UI_WLPERSDATA_PERSONNR").IsUnique();

            entity.Property(e => e.PERSONID).ValueGeneratedNever();
            entity.Property(e => e.ADRESS)
                .HasMaxLength(45)
                .IsUnicode(false);
            entity.Property(e => e.CONAMN)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.EDISP0)
                .HasMaxLength(60)
                .IsUnicode(false);
            entity.Property(e => e.ENAMN)
                .HasMaxLength(40)
                .IsUnicode(false);
            entity.Property(e => e.EPOST)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.EPOST2)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.FENAMN)
                .HasMaxLength(40)
                .IsUnicode(false);
            entity.Property(e => e.FE_NAMN)
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.FNAMN)
                .HasMaxLength(40)
                .IsUnicode(false);
            entity.Property(e => e.FOREDATESIGN)
                .HasMaxLength(17)
                .IsUnicode(false);
            entity.Property(e => e.GRUPP)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.GRUPPSAV)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.HISTDATESIGN)
                .HasMaxLength(17)
                .IsUnicode(false);
            entity.Property(e => e.KONTO)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.M1)
                .HasMaxLength(800)
                .IsUnicode(false);
            entity.Property(e => e.MNAMN)
                .HasMaxLength(40)
                .IsUnicode(false);
            entity.Property(e => e.MOBIL)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.NAMN)
                .HasMaxLength(40)
                .IsUnicode(false);
            entity.Property(e => e.ORT)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.PERSONNR)
                .IsRequired()
                .HasMaxLength(13)
                .IsUnicode(false);
            entity.Property(e => e.POTILLH)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.REGSIGN)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.REGTID)
                .HasMaxLength(19)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.SENASTEBBLAS)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.SENASTEBBSAV)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.TELEFON)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TYP)
                .HasMaxLength(3)
                .IsUnicode(false);
            entity.Property(e => e.UTBKRYSS)
                .HasMaxLength(17)
                .IsUnicode(false);
            entity.Property(e => e.UTBMEMO)
                .HasMaxLength(2000)
                .IsUnicode(false);
            entity.Property(e => e.UTBSUN)
                .HasMaxLength(183)
                .IsUnicode(false);
            entity.Property(e => e.UTSLAS)
                .HasMaxLength(2)
                .IsUnicode(false);
            entity.Property(e => e.UTSSAV)
                .HasMaxLength(2)
                .IsUnicode(false);
            entity.Property(e => e.VAKANT4)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.WLKRYSS)
                .HasMaxLength(300)
                .IsUnicode(false);
        });

        modelBuilder.Entity<WLPERSONAL>(entity =>
        {
            entity.HasKey(e => e.PERSONID).HasName("PK__WLPERSON__0986239E337F44CE");

            entity.ToTable("WLPERSONAL");

            entity.Property(e => e.PERSONID).ValueGeneratedNever();
            entity.Property(e => e.ADRESS)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.ANVID)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.ARBTEL)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.AVD)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.COADRESS)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.ENAMN)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.ENHET)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.EPOST)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.FNAMN)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.INSTITUTION)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.KOSTNSTALLE)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.MOBIL)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.ORG)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.ORT)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.PERSNR)
                .IsRequired()
                .HasMaxLength(13)
                .IsUnicode(false);
            entity.Property(e => e.POSTNR)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.REGSIGN)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.REGTID)
                .HasMaxLength(19)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.SEKEL)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false);
            entity.Property(e => e.SLUTDAT).HasDefaultValue(0);
            entity.Property(e => e.STARTDAT).HasDefaultValue(0);
            entity.Property(e => e.STATUS)
                .HasMaxLength(12)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.TITEL)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasDefaultValue("");
        });

        modelBuilder.Entity<WLPERSONID_ORGID>(entity =>
        {
            entity.HasKey(e => new { e.PERSONID, e.ORGID, e.STATUS }).HasName("PK__WLPERSON__78C17EAC29916D92");

            entity.ToTable("WLPERSONID_ORGID");

            entity.Property(e => e.ORGID)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.STATUS)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasDefaultValue(" ");
            entity.Property(e => e.CHEF)
                .HasMaxLength(2)
                .IsUnicode(false);
            entity.Property(e => e.FOM)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.REGSIGN)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.REGTID)
                .HasMaxLength(19)
                .IsUnicode(false);
            entity.Property(e => e.TOM)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasDefaultValue("");
        });

        modelBuilder.Entity<WLRTFDOK>(entity =>
        {
            entity.HasKey(e => new { e.LOPNR, e.DOKNAMN }).HasName("PK__WLRTFDOK__FFB14AD21AA9674C");

            entity.ToTable("WLRTFDOK");

            entity.Property(e => e.DOKNAMN)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.DOKRAD)
                .HasMaxLength(3000)
                .IsUnicode(false);
            entity.Property(e => e.DOKTYP)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.REGSIGN)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.REGTID)
                .HasMaxLength(19)
                .IsUnicode(false)
                .HasDefaultValue("");
        });

        modelBuilder.Entity<WLTEMP>(entity =>
        {
            entity.HasKey(e => e.LOPNR).HasName("PK__WLTEMP__F5BE5803C58EC9D0");

            entity.ToTable("WLTEMP");

            entity.Property(e => e.LOPNR).ValueGeneratedNever();
            entity.Property(e => e.KOLUMN_A)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.KOLUMN_B)
                .HasMaxLength(400)
                .IsUnicode(false);
            entity.Property(e => e.REGSIGN)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.REGTID)
                .HasMaxLength(19)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.STATUS)
                .HasMaxLength(3)
                .IsUnicode(false);
            entity.Property(e => e.TYP)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
        });

        modelBuilder.Entity<WLTXTDOK>(entity =>
        {
            entity.HasKey(e => new { e.LOPNR, e.DOKNAMN }).HasName("PK__WLTXTDOK__FFB14AD2AF415E0D");

            entity.ToTable("WLTXTDOK");

            entity.Property(e => e.DOKNAMN)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.DOKRAD)
                .HasMaxLength(300)
                .IsUnicode(false);
            entity.Property(e => e.DOKTYP)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.REGSIGN)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.REGTID)
                .HasMaxLength(19)
                .IsUnicode(false)
                .HasDefaultValue("");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}