// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Migration.Models.ModelsWinLas;

public partial class WLANST
{
    public int PERSONID { get; set; }

    public int AR { get; set; }

    public int LOPNR { get; set; }

    public string ANST1 { get; set; }

    public string ANST2 { get; set; }

    public string ANST3 { get; set; }

    public string ANST4 { get; set; }

    public string ANST5 { get; set; }

    public string ANST6 { get; set; }

    public string ANST7 { get; set; }

    public string ANST8 { get; set; }

    public string REGTID { get; set; }

    public string REGSIGN { get; set; }
}