// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Migration.Models.ModelsWinLas;

public partial class WLANSTGRENAR
{
    public int PERSONID { get; set; }

    public int AR { get; set; }

    public int LOPNR { get; set; }

    public string BEFGRP { get; set; }

    public string ASTEGRP { get; set; }

    public string DISP1 { get; set; }

    public string DISP2 { get; set; }

    public string BEFATTNING { get; set; }

    public string LONEFORM { get; set; }

    public string AID { get; set; }

    public string SYSSGR { get; set; }

    public string AVTALOMR { get; set; }

    public string WL_TYP { get; set; }

    public string ANSTNR { get; set; }

    public int? SENASTE_TOM { get; set; }

    public int? FORETRADE_TOM { get; set; }

    public string ORGID { get; set; }

    public string FORV_KORT { get; set; }

    public int? OBEHORIG { get; set; }

    public int? VILANDE { get; set; }

    public string ANSTRAD_ID { get; set; }

    public string ANST { get; set; }

    public string GREN { get; set; }

    public string REGTID { get; set; }

    public string REGSIGN { get; set; }
}