// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Migration.Models.ModelsWinLas;

public partial class WLAVVIKANDECHEF
{
    public int PERSONID { get; set; }

    public int CHEFPERSONID { get; set; }

    public string STATUS { get; set; }

    public string GTOM { get; set; }

    public string REGTID { get; set; }

    public string REGSIGN { get; set; }
}