// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Migration.Models.ModelsWinLas;

public partial class WLENHETER
{
    public int LOPNR { get; set; }

    public string ID { get; set; }

    public string ORGID { get; set; }

    public string MKE { get; set; }

    public int? GFOM { get; set; }

    public int? GTOM { get; set; }

    public string FORV { get; set; }

    public string ENHET { get; set; }

    public string KONTO { get; set; }

    public string REDKONTO { get; set; }

    public string WL_KORT { get; set; }

    public string WL_LANG { get; set; }

    public string REGTID { get; set; }

    public string REGSIGN { get; set; }
}