// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Migration.Models.ModelsWinLas;

public partial class WLGUSERDATum
{
    public string LOGIN { get; set; }

    public int LNR { get; set; }

    public string TYP { get; set; }

    public string KOLUMN1 { get; set; }

    public string KOLUMN2 { get; set; }

    public string REGTID { get; set; }

    public string REGSIGN { get; set; }
}