// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Migration.Models.ModelsWinLas;

public partial class WLGUSER
{
    public int LOPNR { get; set; }

    public string MKE { get; set; }

    public int? PERSONID { get; set; }

    public int? TOMDAT { get; set; }

    public string LOGIN { get; set; }

    public string SIGN { get; set; }

    public string NAMN { get; set; }

    public string BEF { get; set; }

    public string CHEF { get; set; }

    public string TFN { get; set; }

    public string FRITT { get; set; }

    public string RH { get; set; }

    public string PSW { get; set; }

    public string PSWDAT { get; set; }

    public string REGTID { get; set; }

    public string REGSIGN { get; set; }
}