// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Migration.Models.ModelsWinLas;

public partial class WLJOURTABELL
{
    public int LOPNR { get; set; }

    public string ID { get; set; }

    public string TEXT { get; set; }

    public string MARKE { get; set; }

    public int? RADNR { get; set; }

    public string REGTID { get; set; }

    public string REGSIGN { get; set; }
}