// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Migration.Models.ModelsWinLas;

public partial class WLJOURNAL
{
    public int PERSONID { get; set; }

    public int LOPNR { get; set; }

    public int? FROMDAT { get; set; }

    public int? TOMDAT { get; set; }

    public string EVENT { get; set; }

    public string FRITEXT { get; set; }

    public string BEFGRP { get; set; }

    public string FV { get; set; }

    public string SIGN { get; set; }

    public string AKTIV { get; set; }

    public string ANTECKN { get; set; }

    public string REGTID { get; set; }

    public string REGSIGN { get; set; }
}