// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Migration.Models.ModelsWinLas;

public partial class WLKOMPTAB
{
    public string ID { get; set; }

    public string MKE { get; set; }

    public string DEL1 { get; set; }

    public string DEL2 { get; set; }

    public string DEL3 { get; set; }

    public string DEL4 { get; set; }

    public string DEL5 { get; set; }

    public string K_KORT { get; set; }

    public string K_LONG { get; set; }

    public string REGTID { get; set; }

    public string REGSIGN { get; set; }
}