// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Migration.Models.ModelsWinLas;

public partial class WLKOMPETEN
{
    public int PERSONID { get; set; }

    public int LOPNR { get; set; }

    public string ID { get; set; }

    public string KOMP { get; set; }

    public string SPANN { get; set; }

    public string B_L { get; set; }

    public string UI { get; set; }

    public string VB1 { get; set; }

    public string VB2 { get; set; }

    public string VB3 { get; set; }

    public string VB4 { get; set; }

    public string VB5 { get; set; }

    public string VB6 { get; set; }

    public string FRITT { get; set; }

    public string AR { get; set; }

    public string ATTEST { get; set; }

    public string SIGNDAT { get; set; }

    public string REGTID { get; set; }

    public string REGSIGN { get; set; }
}