// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Migration.Models.ModelsWinLas;

public partial class WLLETTER
{
    public string RECEIVER { get; set; }

    public string SENDER { get; set; }

    public string STAMP { get; set; }

    public string STATUS { get; set; }

    public string COMMON { get; set; }

    public string RUBRIK { get; set; }

    public string LETTER { get; set; }

    public string REGTID { get; set; }

    public string REGSIGN { get; set; }
}