// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Migration.Models.ModelsWinLas;

public partial class WLLOGG
{
    public int LOPNR { get; set; }

    public int? PERSONID { get; set; }

    public string TYP { get; set; }

    public string EVENTNR { get; set; }

    public string TEXT { get; set; }

    public int? LOGGDAT { get; set; }

    public string BOCK { get; set; }

    public string ANSTID { get; set; }

    public string ORGID { get; set; }

    public int? ANSTTOM { get; set; }

    public string DISP1 { get; set; }

    public string NOTERING { get; set; }

    public string SIGNATUR { get; set; }

    public string REGTID { get; set; }

    public string REGSIGN { get; set; }
}