// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
namespace Migration.Models.ModelsWinLas;

public partial class WLMALLAR
{
    public int LOPNR { get; set; }

    public string SIGNATUR { get; set; }

    public string MALLNAMN { get; set; }

    public string MALLRAD { get; set; }

    public string REGTID { get; set; }

    public string REGSIGN { get; set; }
}