// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Migration.Models.ModelsWinLas;

public partial class WLORGTRADET
{
    public string TYP { get; set; }

    public string ORGID { get; set; }

    public string WL_KORT { get; set; }

    public string WL_LANG { get; set; }

    public string PARENT { get; set; }

    public string ORGGREN { get; set; }

    public string REGTID { get; set; }

    public string REGSIGN { get; set; }
}