// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Migration.Models.ModelsWinLas;

public partial class WLPERSONID_ORGID
{
    public int PERSONID { get; set; }

    public string ORGID { get; set; }

    public string CHEF { get; set; }

    public string STATUS { get; set; }

    public string FOM { get; set; }

    public string TOM { get; set; }

    public string REGTID { get; set; }

    public string REGSIGN { get; set; }
}