// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Migration.Models.ModelsWinLas;

public partial class WLPERSONAL
{
    public int PERSONID { get; set; }

    public string PERSNR { get; set; }

    public string SEKEL { get; set; }

    public string STATUS { get; set; }

    public string FNAMN { get; set; }

    public string ENAMN { get; set; }

    public string ADRESS { get; set; }

    public string COADRESS { get; set; }

    public string POSTNR { get; set; }

    public string ORT { get; set; }

    public string ARBTEL { get; set; }

    public string MOBIL { get; set; }

    public string TITEL { get; set; }

    public string KOSTNSTALLE { get; set; }

    public string INSTITUTION { get; set; }

    public int? STARTDAT { get; set; }

    public int? SLUTDAT { get; set; }

    public string ANVID { get; set; }

    public string EPOST { get; set; }

    public string ORG { get; set; }

    public string AVD { get; set; }

    public string ENHET { get; set; }

    public string REGTID { get; set; }

    public string REGSIGN { get; set; }
}