// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Migration.Models.ModelsWinLas;

public partial class WLPERSDATum
{
    public int PERSONID { get; set; }

    public string PERSONNR { get; set; }

    public short? SKYDD { get; set; }

    public string NAMN { get; set; }

    public string FNAMN { get; set; }

    public string MNAMN { get; set; }

    public string ENAMN { get; set; }

    public string ADRESS { get; set; }

    public string ORT { get; set; }

    public string CONAMN { get; set; }

    public string TYP { get; set; }

    public string TELEFON { get; set; }

    public string MOBIL { get; set; }

    public string POTILLH { get; set; }

    public string KONTO { get; set; }

    public string FENAMN { get; set; }

    public string FE_NAMN { get; set; }

    public string EPOST { get; set; }

    public string EPOST2 { get; set; }

    public string M1 { get; set; }

    public string UTBSUN { get; set; }

    public string EDISP0 { get; set; }

    public string UTBKRYSS { get; set; }

    public string UTBMEMO { get; set; }

    public int? KONVAVA { get; set; }

    public int? ARKDATE { get; set; }

    public int? SISTDATE { get; set; }

    public int? FOREDATE { get; set; }

    public int? KONVVIK { get; set; }

    public int? KONVSAV { get; set; }

    public int? SENASTESAV { get; set; }

    public string GRUPPSAV { get; set; }

    public int? SENASTEVIK { get; set; }

    public int? SENASTEAVA { get; set; }

    public int? SENASTEKONV { get; set; }

    public int? SENASTEPRJ { get; set; }

    public string GRUPP { get; set; }

    public short? JOURNAL { get; set; }

    public string HISTDATESIGN { get; set; }

    public string FOREDATESIGN { get; set; }

    public string SENASTEBBLAS { get; set; }

    public string SENASTEBBSAV { get; set; }

    public string UTSLAS { get; set; }

    public string UTSSAV { get; set; }

    public int? SENASTELAS { get; set; }

    public short? T1 { get; set; }

    public short? T2 { get; set; }

    public short? T3 { get; set; }

    public short? T4 { get; set; }

    public short? T5 { get; set; }

    public short? T6 { get; set; }

    public short? T7 { get; set; }

    public short? T8 { get; set; }

    public short? T9 { get; set; }

    public short? T10 { get; set; }

    public short? T11 { get; set; }

    public short? T12 { get; set; }

    public short? T13 { get; set; }

    public short? T14 { get; set; }

    public short? T15 { get; set; }

    public short? T16 { get; set; }

    public short? T17 { get; set; }

    public short? T18 { get; set; }

    public short? T19 { get; set; }

    public int? FOREDATESAV { get; set; }

    public short? T21 { get; set; }

    public int? EJLASDAT { get; set; }

    public short? T23 { get; set; }

    public short? T24 { get; set; }

    public short? T25 { get; set; }

    public short? T26 { get; set; }

    public short? T27 { get; set; }

    public short? T28 { get; set; }

    public short? T29 { get; set; }

    public short? T30 { get; set; }

    public string VAKANT4 { get; set; }

    public string WLKRYSS { get; set; }

    public short? KR1 { get; set; }

    public short? KR2 { get; set; }

    public short? KR3 { get; set; }

    public short? KR4 { get; set; }

    public short? KR5 { get; set; }

    public short? KR6 { get; set; }

    public short? KR7 { get; set; }

    public short? KR8 { get; set; }

    public short? KR9 { get; set; }

    public short? KR10 { get; set; }

    public short? KR11 { get; set; }

    public short? KR12 { get; set; }

    public short? KR13 { get; set; }

    public short? KR14 { get; set; }

    public string REGTID { get; set; }

    public string REGSIGN { get; set; }
}