// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Migration.Models.ModelsWinLas;

public partial class WLTEMP
{
    public int LOPNR { get; set; }

    public string TYP { get; set; }

    public string STATUS { get; set; }

    public string KOLUMN_A { get; set; }

    public string KOLUMN_B { get; set; }

    public string REGTID { get; set; }

    public string REGSIGN { get; set; }
}