// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Migration.Models.ModelsWinLas;

public partial class WLTXTDOK
{
    public int LOPNR { get; set; }

    public string DOKTYP { get; set; }

    public string DOKNAMN { get; set; }

    public string DOKRAD { get; set; }

    public string REGTID { get; set; }

    public string REGSIGN { get; set; }
}