// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(LasSystemDbContext))]
    [Migration("20251125125338_update1")]
    partial class update1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Anstallning", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnstallningsKlassificeringKod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AnstallningsKlassificeringTyp")
                        .HasColumnType("int");

                    b.Property<string>("Anstallningsnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvgangsorsakKod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AvgangsorsaksTyp")
                        .HasColumnType("int");

                    b.Property<string>("AvtalKod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BefattningsGruppering")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BefattningsKod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BefattninsText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("From")
                        .HasColumnType("date");

                    b.Property<bool>("Last")
                        .HasColumnType("bit");

                    b.Property<int>("LoneformTyp")
                        .HasColumnType("int");

                    b.Property<string>("OrganisationsKod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganisationsText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Regtid")
                        .HasColumnType("datetime2");

                    b.Property<float>("Sysselsattningsgrad")
                        .HasColumnType("real");

                    b.Property<DateOnly?>("Tom")
                        .HasColumnType("date");

                    b.Property<bool>("Vilande")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Anstallningar");
                });

            modelBuilder.Entity("Domain.Entities.Kund", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AnvandVarjeArbetsDagSomEnPerionVidSava")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("BrytDatum")
                        .HasColumnType("date");

                    b.Property<string>("ConnectionStringWinLas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ForetradeAllmanDagar")
                        .HasColumnType("int");

                    b.Property<int>("ForetradeSavDagar")
                        .HasColumnType("int");

                    b.Property<int>("ImportSystemTyp")
                        .HasColumnType("int");

                    b.Property<int>("KonverteringLASDagar")
                        .HasColumnType("int");

                    b.Property<int>("KonverteringSavDagar")
                        .HasColumnType("int");

                    b.Property<int>("KonverteringVikDagar")
                        .HasColumnType("int");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("OmraknadWinLas")
                        .HasColumnType("date");

                    b.Property<int>("Pensionsalder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Kunder");
                });

            modelBuilder.Entity("Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnstallningsTid")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ForetradeAllmanDatum")
                        .HasColumnType("date");

                    b.Property<int>("ForetradeAllmanIdagTid")
                        .HasColumnType("int");

                    b.Property<int>("ForetradeSavIdagTid")
                        .HasColumnType("int");

                    b.Property<int>("HistoriskTid")
                        .HasColumnType("int");

                    b.Property<DateOnly>("HistorisktBrytDatum")
                        .HasColumnType("date");

                    b.Property<int>("KonverteringAvaIdagTid")
                        .HasColumnType("int");

                    b.Property<int>("KonverteringSavIdagTid")
                        .HasColumnType("int");

                    b.Property<int>("KonverteringVikIdagTid")
                        .HasColumnType("int");

                    b.Property<Guid>("KundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Personnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("SenatsteAnstallning")
                        .HasColumnType("date");

                    b.Property<int>("TillagsTid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KundId");

                    b.ToTable("Personer");
                });

            modelBuilder.Entity("Domain.Entities.WinLasData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ForetradeAllmanIdagTid")
                        .HasColumnType("int");

                    b.Property<int>("ForetradeAllmanSenasteTid")
                        .HasColumnType("int");

                    b.Property<int>("ForetradeSavIdagTid")
                        .HasColumnType("int");

                    b.Property<int>("ForetradeSavSenasteTid")
                        .HasColumnType("int");

                    b.Property<int>("KonverteringSavIdagTid")
                        .HasColumnType("int");

                    b.Property<int>("KonverteringSavSenasteTid")
                        .HasColumnType("int");

                    b.Property<int>("KonverteringVikIdagTid")
                        .HasColumnType("int");

                    b.Property<int>("KonverteringVikSenasteTid")
                        .HasColumnType("int");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Senaste")
                        .HasColumnType("date");

                    b.Property<int>("TotalAnstallningsTid")
                        .HasColumnType("int");

                    b.Property<int>("WinLasPersonid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("WinLasData");
                });

            modelBuilder.Entity("Domain.Entities.Anstallning", b =>
                {
                    b.HasOne("Domain.Entities.Person", "Person")
                        .WithMany("Anstallningar")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Domain.Entities.Person", b =>
                {
                    b.HasOne("Domain.Entities.Kund", "Kund")
                        .WithMany("Personer")
                        .HasForeignKey("KundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kund");
                });

            modelBuilder.Entity("Domain.Entities.WinLasData", b =>
                {
                    b.HasOne("Domain.Entities.Person", "Person")
                        .WithOne("WinLasData")
                        .HasForeignKey("Domain.Entities.WinLasData", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Domain.Entities.Kund", b =>
                {
                    b.Navigation("Personer");
                });

            modelBuilder.Entity("Domain.Entities.Person", b =>
                {
                    b.Navigation("Anstallningar");

                    b.Navigation("WinLasData")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
